/*
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.backend.wasm.lower

import org.jetbrains.kotlin.backend.common.BodyLoweringPass
import org.jetbrains.kotlin.backend.wasm.WasmBackendContext
import org.jetbrains.kotlin.ir.declarations.IrDeclaration
import org.jetbrains.kotlin.ir.declarations.IrVariable
import org.jetbrains.kotlin.ir.expressions.*
import org.jetbrains.kotlin.ir.types.isNothing
import org.jetbrains.kotlin.ir.types.isNullableAny
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid

/**
 * Eliminates redundant box-then-unbox round-trips introduced by autoboxing
 * and type-operator lowering.
 *
 * After [WasmTypeOperatorLowering], an implicit cast from a type-parameter
 * return type generates a full Kotlin cast wrapped in an [IrComposite].
 * When the result is immediately re-boxed by autoboxing, the chain becomes
 *
 *     boxIntrinsic(COMPOSITE { VAR tmp = e; IF (typecheck) unboxIntrinsic(tmp) ELSE throw })
 *
 * where `e` already returns a reference type at the Wasm level. The type-check,
 * unbox, and re-box are a no-op. Removing them also exposes the original call
 * to [WasmTailCallLowering], enabling `return_call_ref` for lambda dispatch
 * chains.
 */
internal class WasmBoxUnboxEliminationLowering(private val context: WasmBackendContext) : BodyLoweringPass {
    private val boxIntrinsic = context.wasmSymbols.boxIntrinsic
    private val unboxIntrinsic = context.wasmSymbols.unboxIntrinsic

    override fun lower(irBody: IrBody, container: IrDeclaration) {
        irBody.transformChildrenVoid(object : IrElementTransformerVoid() {
            override fun visitCall(expression: IrCall): IrExpression {
                expression.transformChildrenVoid(this)
                if (expression.symbol != boxIntrinsic) return expression
                // The elimination is only safe when the box target type is Any?,
                // because the initializer returns (ref null AnyHeap) at the Wasm
                // level. For narrower target types like Number, the Wasm heap
                // types differ and the validator would reject the module.
                val boxTargetType = expression.typeArguments[1] ?: return expression
                if (!boxTargetType.isNullableAny()) return expression
                val arg = expression.arguments[0] ?: return expression
                return extractBoxedValue(arg) ?: expression
            }
        })
    }

    /**
     * Given the argument to `boxIntrinsic`, returns the underlying reference-typed
     * expression when the box is redundant, or null when it is not.
     */
    private fun extractBoxedValue(arg: IrExpression): IrExpression? = when (arg) {
        // box(unbox(e)) → e
        is IrCall ->
            if (arg.symbol == unboxIntrinsic) arg.arguments[0] else null

        // box(COMPOSITE { VAR tmp = e; type-check-and-unbox(tmp) }) → e
        is IrComposite ->
            extractCastRoundTripValue(arg)

        else -> null
    }

    /**
     * Matches the IR pattern generated by [WasmTypeOperatorLowering.lowerCast]
     * for implicit casts from type-parameter return types.
     *
     * The pattern is
     *
     *     COMPOSITE { VAR tmp: Any? = e; <branches ending in unboxIntrinsic(tmp)> }
     *
     * Returns `e` when the variable already holds a reference type, meaning the
     * surrounding box(composite) is a no-op at the Wasm level.
     */
    private fun extractCastRoundTripValue(composite: IrComposite): IrExpression? {
        val statements = composite.statements
        if (statements.size != 2) return null

        val variable = statements[0] as? IrVariable ?: return null
        val initializer = variable.initializer ?: return null

        // The variable must hold a reference type (not an inlined primitive).
        if (context.inlineClassesUtils.isTypeInlined(initializer.type)) return null

        // Every non-throwing path through the second statement must end with
        // unboxIntrinsic of this variable.
        val secondStatement = statements[1] as? IrExpression ?: return null
        if (!endsInUnboxOf(secondStatement, variable)) return null

        return initializer
    }

    /**
     * Returns true when every non-throwing execution path through [expr]
     * terminates with `unboxIntrinsic(GET_VAR [variable])`.
     */
    private fun endsInUnboxOf(expr: IrExpression, variable: IrVariable): Boolean = when (expr) {
        is IrCall ->
            expr.symbol == unboxIntrinsic &&
                    (expr.arguments[0] as? IrGetValue)?.symbol == variable.symbol

        is IrWhen ->
            expr.branches.all { branch ->
                endsInUnboxOf(branch.result, variable) || branch.result.type.isNothing()
            }

        else -> false
    }
}
